name: pr
on: [pull_request]

jobs:
  build:
    name: pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install virtualenv
    - run: make
    - run: venv/bin/pre-commit run --all-files --show-diff-on-failure
